[dev] Modify test files, verify git actions

diff --git a/.github/workflows/data_preprocessing_workflow.yaml b/.github/workflows/data_preprocessing_workflow.yaml
--- a/.github/workflows/data_preprocessing_workflow.yaml
+++ b/.github/workflows/data_preprocessing_workflow.yaml
@@ -7,8 +7,8 @@ on:
       - 'data_pipeline/tests/data_preprocessing/**'        # Monitor all changes in tests
 
 jobs:
-  # Job for installing dependencies and caching them
-  install_dependencies:
+  # Job for installing dependencies and running tests
+  test:
     runs-on: ubuntu-latest
 
     steps:
@@ -20,34 +20,23 @@ jobs:
         with:
           python-version: '3.12.7'  # Specify the Python version you need
 
-      # - name: Cache Python packages
-      #   uses: actions/cache@v3
-      #   with:
-      #     path: ~/.cache/pip
-      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-pip-
+      - name: Cache Python packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r data_pipeline/requirements.txt
 
-  # Job for running each test file separately
-  test:
-    runs-on: ubuntu-latest
-    needs: install_dependencies  # Ensure dependencies are installed before running tests
-
-    strategy:
-      matrix:
-        test_file: 
-          - "data_pipeline/tests/data_preprocessing/test_data_cleaning_pandas.py"
-          - "data_pipeline/tests/data_preprocessing/test_aspect_extraction.py"  # Add more test files as needed
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Run tests
+      - name: Run all tests
         run: |
-          python -m unittest ${test_file}
+          # Find and run all test files in the specified directory
+          for test_file in data_pipeline/tests/data_preprocessing/test_*.py; do
+            echo "Running $test_file"
+            python -m unittest "$test_file" || exit 1  # Exit if any test fails
+          done
